version: "3"

services:
  # Base de données
  wordpress-db:
    container_name: wordpress-db
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: SuperPassword1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: SuperPassword
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater

  wordpress:
    container_name: wordpress
    depends_on:
      - wordpress-db
    image: papamica/superwordpress
    volumes:
      - ./data/html:/var/www/html
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: SuperPassword
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_ADMIN_USERNAME: admin
      WORDPRESS_ADMIN_PASSWORD: papamica
      WORDPRESS_ADMIN_EMAIL: papamica@exemple.com
      WORDPRESS_LANGUAGE: "fr_FR"
      PLUGINS_TO_INSTALL: "mainwp-child elementor updraftplus header-footer-elementor envato-elements include-matomo jetpack wp-mail-smtp wordpress-seo duplicate-post autoptimize contact-form-7"
      PLUGINS_TO_REMOVE: "hello akismet"
      THEMES_TO_INSTALL: "hello-elementor"
      THEMES_TO_REMOVE: "twentytwenty twentytwentytwo twentytwentyone"
      WORDPRESS_URL: 
      WORDPRESS_TITLE: wordpress-test
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater